# Generated by Django 5.0 on 2024-01-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metauser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='description',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='instagram_username',
        ),
    ]
